---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: kube-proxy
  namespace: kube-system
  labels:
    app: kubernetes
    component: proxy
spec:
  template:
    metadata:
      labels:
        app: kubernetes
        component: proxy
    spec:
      hostNetwork: true
      containers:
        - name: kube-proxy
          image: ${hyperkube}:${kube_version}
          securityContext:
            privileged: true
          command:
            - /bin/bash
            - -c
            - "sed -i /etc/kubeconfig/kubeconfig.yaml \
                -e s,{{token}},$(cat /var/run/secrets/kubernetes.io/serviceaccount/token),g && \
                exec /hyperkube proxy \
                  --master=https://${kube_fqdn} \
                  --kubeconfig=/etc/kubeconfig/kubeconfig.yaml \
                  --proxy-mode=iptables"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10249
            initialDelaySeconds: 15
            timeoutSeconds: 1
          volumeMounts:
            - name: kubeconfig
              mountPath: /etc/kubeconfig
      volumes:
        - name: kubeconfig
          configMap:
            name: service-account-kubeconfig
