---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kube-ingress-traefik-dns
  namespace: kube-system
  labels:
    app: kube-ingress-traefik
    component: dns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-ingress-traefik
        component: dns
    spec:
      containers:
        - name: vault-sidekick
          image: quay.io/roboll/vault-sidekick:v0.0.9.11
          args:
            - -logtostderr=true
            - -tls-skip-verify=true
            - -output=/etc/secrets
            - -cn=aws:${dns_path}:fmt=awsenv,file=aws.env,export=true
          env:
            - name: VAULT_ADDR
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: address
            - name: VAULT_CACERT
              value: /etc/vault/ca.pem
            - name: VAULT_SIDEKICK_AUTH_METHOD
              value: approle
            - name: VAULT_SIDEKICK_ROLE_ID
              valueFrom:
                configMapKeyRef:
                  name: vault-role-kube-ingress-dns
                  key: role-id
            - name: VAULT_SIDEKICK_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: vault-secret-kube-ingress-dns
                  key: secret-id
          volumeMounts:
            - mountPath: /etc/secrets
              name: secrets
        - name: dns-controller
          image: quay.io/roboll/kube-dns-controller:v0.0.2
          command:
            - /bin/sh
            - -c
            - sleep 10 &&
              source /etc/secrets/aws.env &&
              exec /dns-controller --publish-service=$(POD_NAMESPACE)/kube-ingress-traefik
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /etc/secrets
              name: secrets
              readOnly: true
      volumes:
        - name: secrets
          emptyDir: {}
