---
kind: Service
apiVersion: v1
metadata:
  name: kube-scheduler
  namespace: kube-system
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10251"
  labels:
    name: kube-scheduler
spec:
  selector:
    app: kubernetes
    component: scheduler
  ports:
  - name: metrics
    port: 10251
    protocol: TCP

---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    app: kubernetes
    component: scheduler
spec:
  template:
    metadata:
      labels:
        app: kubernetes
        component: scheduler
    spec:
      nodeSelector:
        role: controller
      containers:
        - name: kube-scheduler
          image: ${hyperkube}:${kube_version}
          command:
            - /bin/bash
            - -c
            - "sed -i /etc/kubeconfig/kubeconfig.yaml \
                -e s,{{token}},$(cat /var/run/secrets/kubernetes.io/serviceaccount/token),g && \
                exec /hyperkube scheduler \
                  --master=https://${kube_fqdn} \
                  --kubeconfig=/etc/kubeconfig/kubeconfig.yaml \
                  --leader-elect=true"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10251
            initialDelaySeconds: 15
            timeoutSeconds: 1
          volumeMounts:
            - name: kubeconfig
              mountPath: /etc/kubeconfig
      volumes:
        - name: kubeconfig
          configMap:
            name: service-account-kubeconfig
