---
kind: ConfigMap
apiVersion: v1
metadata:
  name: service-account-kubeconfig
  namespace: kube-system
data:
  kubeconfig.yaml: |-
    apiVersion: v1
    kind: Config
    users:
      - name: service-account
        user:
          token: {{token}}
    clusters:
      - name: local
        cluster:
          certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    contexts:
      - context:
          cluster: local
          user: service-account
        name: service-account-context
    current-context: service-account-context
