#cloud-config
hostname: ${instance_name}.${domain}
coreos:
  update:
    reboot-strategy: off

  units:
    - name: vault-ssh.service
      command: start
      content: |
        [Service]
        Type=oneshot

        ExecStartPre=/usr/bin/rkt fetch --trust-keys-from-https ${vault_ssh_image}
        ExecStart=/usr/bin/rkt image extract --rootfs-only --overwrite ${vault_ssh_image} /tmp/vault-ssh
        ExecStartPost=/tmp/vault-ssh/link.sh

    - name: vault-login.service
      command: start
      content: |
        [Service]
        Type=oneshot
        FailureAction=reboot
        ExecStart=/opt/bin/vault-login.sh

    - name: vault-renew-token.service
      content: |
        [Service]
        Type=simple
        FailureAction=reboot
        ExecStart=/opt/bin/vault-renew-token.sh

    - name: vault-renew-token.timer
      command: start
      content: |
        [Timer]
        OnActiveSec=12h
        OnUnitActiveSec=12h

    - name: dev-xvdb-format.service
      command: start
      content: |
        [Unit]
        Requires=dev-xvdb.device
        After=dev-xvdb.device

        Before=var-lib-etcd.mount
        ConditionPathExists=!/var/lib/etcd.formatted

        [Service]
        Type=oneshot
        ExecStart=/usr/sbin/wipefs -f /dev/xvdb
        ExecStart=/usr/sbin/mkfs.ext4 /dev/xvdb
        ExecStartPost=/bin/touch /var/lib/etcd.formatted

    - name: var-lib-etcd.mount
      command: start
      content: |
        [Unit]
        Requires=dev-xvdb-format.service
        After=dev-xvbd-format.service

        [Mount]
        What=/dev/xvdb
        Where=/var/lib/etcd
        Type=ext4

    - name: docker.service
      command: start
      drop-ins:
        - name: 99-mount-flags.conf
          content: |
            [Service]
            MountFlags=shared

    - name: kubelet.service
      command: start
      content: |
        [Unit]
        Requires=docker.service
        After=docker.service

        [Service]
        Restart=always
        RestartSec=10

        ExecStartPre=/usr/bin/mkdir -p /var/run/kubelet
        ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests

        ExecStartPre=/opt/bin/kube-ca.pem
        ExecStartPre=/usr/bin/docker run \
          -e HYPERKUBE=${hyperkube}:${kube_version}  \
          -e KUBE_FQDN=${kube_fqdn} \
          -e KUBE_CA=/etc/ssl/kube/ca.pem \
          -e ETCD_PEERS=${etcd_peers} \
          -e ETCD_NODES=${etcd_nodes} \
          --volume /etc/kubernetes/manifests/:/etc/kubernetes/manifests/ \
          quay.io/roboll/kube-bootstrap:alpha /opt/bin/copy-manifest.sh

        ExecStart=/usr/bin/docker run \
          --net=host \
          --pid=host \
          --privileged=true \
          --volume=/:/rootfs/:ro \
          --volume=/sys/:/sys/:ro \
          --volume=/dev/:/dev/ \
          --volume=/var/run/:/var/run/:rw \
          --volume=/etc/kubernetes/:/etc/kubernetes/ \
          --volume=/var/lib/docker/:/var/lib/docker/:rw \
          --volume=/var/lib/kubelet/:/var/lib/kubelet/:shared \
          ${hyperkube}:${kube_version} \
            /kubelet \
              --pod-manifest-path=/etc/kubernetes/manifests \
              --kubeconfig=/var/lib/kubelet/kubeconfig-local.yaml \
              --require-kubeconfig \
              --register-schedulable=false \
              --lock-file=/var/run/kubelet/lock \
              --exit-on-lock-contention=true \
              --node-labels=role=controller \
              --allow-privileged=true

write_files:
  - path: /etc/ssl/vault/ca.pem
    permissions: 0600
    encoding: base64
    content: |
      ${vault_ca_cert_pem_b64}

  - path: /etc/vault/ssh.hcl
    permissions: 0600
    content: |
      allowed_roles = "*"
      vault_addr = "${vault_address}"
      ca_cert = "/etc/ssl/vault/ca.pem"

  - path: /opt/bin/vault-login.sh
    permissions: 0700
    content: |
      #!/bin/bash
      set -eo pipefail

      mkdir -p /var/lib/vault
      nonce="$(cat /etc/machine-id | base64)"
      pkcs="$(curl ${vault_curl_opts} --cacert /etc/ssl/vault/ca.pem \
        http://169.254.169.254/latest/dynamic/instance-identity/pkcs7 | tr -d '\n')"

      curl ${vault_curl_opts} --cacert /etc/ssl/vault/ca.pem \
        -X POST -H "Content-Type: application/json" \
        -d "{\"pkcs7\":\"$pkcs\",\"role\":\"${vault_instance_role}\",\"nonce\":\"$nonce\"}" \
        ${vault_address}/v1/auth/aws-ec2/login | \
        sed -re 's/.*"client_token":"([^"]*)".*/\1/g' > /var/lib/vault/token

  - path: /opt/bin/vault-renew-token.sh
    permissions: 0700
    content: |
      #!/bin/bash
      set -eo pipefail

      token="$(cat /var/lib/vault/token)"
      curl ${vault_curl_opts} --cacert /etc/ssl/vault/ca.pem \
        -X POST -H "X-Vault-Token: $token" \
        -d '{"increment": "24h"}' \
        ${vault_address}/v1/auth/token/renew-self > /dev/null

  - path: /opt/bin/kube-ca.sh
    permissions: 0700
    content: |
      #! /bin/bash
      set -eo pipefail

      mkdir -p /etc/ssl/kube
      curl -sSf --ca-file /etc/ssl/vault/ca.pem \
        -z /etc/ssl/kube/ca.pem \
        -o /etc/ssl/kube/ca.pem \
        ${vault_address}/${kube_pki_mount}/ca/pem

  - path: /etc/kube-bootstrap/env
    permissions: 0600
    content: |
      export VAULT_ADDR=${vault_address}
      export ETCD_VAULT_PKI_MOUNT=${etcd_pki_mount}
      export KUBE_VAULT_PKI_MOUNT=${kube_pki_mount}
      export SVC_ACCT_PUBKEY=${service_account_pubkey}
      export SVC_ACCT_PRIVKEY=${service_account_privkey}

  - path: /var/lib/kubelet/kubeconfig-local.yaml
    permissions: 0700
    content: |
      kind: Config
      apiVersion: v1
      current-context: kube
      clusters:
        - name: kubernetes
          cluster:
            server: http://localhost:8080
      users:
        - name: user
      contexts:
        - name: kube
          context:
            cluster: kubernetes
            user: user
