#cloud-config
hostname: ${instance_name}.${domain}
coreos:
  update:
    reboot-strategy: off

  units:
    - name: vault-ssh.service
      command: start
      content: |
        [Service]
        Type=oneshot

        ExecStartPre=/usr/bin/rkt fetch --trust-keys-from-https ${vault_ssh_image}
        ExecStart=/usr/bin/rkt image extract --rootfs-only --overwrite ${vault_ssh_image} /tmp/vault-ssh
        ExecStartPost=/tmp/vault-ssh/link.sh

    - name: vault-login.service
      command: start
      content: |
        [Service]
        Type=oneshot
        FailureAction=reboot
        ExecStart=/opt/bin/vault-login.sh

    - name: vault-renew-token.service
      content: |
        [Service]
        Type=simple
        FailureAction=reboot
        ExecStart=/opt/bin/vault-renew-token.sh

    - name: vault-renew-token.timer
      command: start
      content: |
        [Timer]
        OnActiveSec=12h
        OnUnitActiveSec=12h

    - name: dev-xvdb-format.service
      command: start
      content: |
        [Unit]
        Requires=dev-xvdb.device
        After=dev-xvdb.device

        Before=var-lib-etcd.mount
        ConditionPathExists=!/var/lib/etcd.formatted

        [Service]
        Type=oneshot
        ExecStart=/usr/sbin/wipefs -f /dev/xvdb
        ExecStart=/usr/sbin/mkfs.ext4 /dev/xvdb
        ExecStartPost=/bin/touch /var/lib/etcd.formatted

    - name: var-lib-etcd.mount
      command: start
      content: |
        [Unit]
        Requires=dev-xvdb-format.service
        After=dev-xvbd-format.service

        [Mount]
        What=/dev/xvdb
        Where=/var/lib/etcd
        Type=ext4

    - name: docker.service
      command: start
      drop-ins:
        - name: 99-mount-flags.conf
          content: |
            [Service]
            MountFlags=shared

    - name: kubelet.service
      command: start
      content: |
        [Unit]
        Requires=docker.service
        After=docker.service

        ConditionPathExists=!/var/run/kubelet/lock

        [Service]
        Restart=always
        RestartSec=10

        Environment=KUBELET_ACI=${hyperkube}
        Environment=KUBELET_VERSION=${kube_version}
        Environment=HYPERKUBE=${hyperkube}:${kube_version}

        Environment=ETCD_INITIAL_CLUSTER=${etcd_peers}
        Environment=ETCD_PKI_MOUNT=${etcd_pki_mount}

        Environment=SVC_ACCT_PUBKEY=${service_account_pubkey}
        Environment=SVC_ACCT_PRIVKEY=${service_account_privkey}
        Environment=KUBE_PKI_MOUNT=${kube_pki_mount}
        Environment=KUBE_FQDN=${kube_fqdn}

        Environment=VAULT_ADDR=${vault_address}

        ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
        ExecStartPre=/usr/bin/rkt run --trust-keys-from-https --inherit-env \
          --volume manifests,kind=host,source=/etc/kubernetes/manifests \
          --mount volume=manifests,target=/etc/kubernetes/manifests \
          quay.io/roboll/kube-bootstrap:alpha --exec /opt/bin/copy-manifests.sh

        Environment="RKT_OPTS=--volume manifests,kind=host,source=/etc/kubernetes/manifests \
        --mount volume=manifests,target=/etc/kubernetes/manifests"

        ExecStart=/usr/lib/coreos/kubelet-wrapper \
          --pod-manifest-path=/etc/kubernetes/manifests \
          --node-labels=role=controller \
          --lock-file=/var/run/kubelet/lock \
          --exit-on-lock-contention=true \
          --allow-privileged=true

write_files:
  - path: /etc/ssl/vault/ca.pem
    permissions: 0600
    encoding: base64
    content: |
      ${vault_ca_cert_pem_b64}

  - path: /etc/vault/ssh.hcl
    permissions: 0600
    content: |
      allowed_roles = "*"
      vault_addr = "${vault_address}"
      ca_cert = "/etc/ssl/vault/ca.pem"

  - path: /opt/bin/vault-login.sh
    permissions: 0700
    content: |
      #!/bin/bash
      set -eo pipefail

      mkdir -p /var/lib/vault
      nonce="$(cat /etc/machine-id | base64)"
      pkcs="$(curl ${vault_curl_opts} --cacert /etc/ssl/vault/ca.pem \
        http://169.254.169.254/latest/dynamic/instance-identity/pkcs7 | tr -d '\n')"

      curl ${vault_curl_opts} --cacert /etc/ssl/vault/ca.pem \
        -X POST -H "Content-Type: application/json" \
        -d "{\"pkcs7\":\"$pkcs\",\"role\":\"${vault_instance_role}\",\"nonce\":\"$nonce\"}" \
        ${vault_address}/v1/auth/aws-ec2/login | \
        sed -re 's/.*"client_token":"([^"]*)".*/\1/g' > /var/lib/vault/token

  - path: /opt/bin/vault-renew-token.sh
    permissions: 0700
    content: |
      #!/bin/bash
      set -eo pipefail

      token="$(cat /var/lib/vault/token)"
      curl ${vault_curl_opts} --cacert /etc/ssl/vault/ca.pem \
        -X POST -H "X-Vault-Token: $token" \
        -d '{"increment": "24h"}' \
        ${vault_address}/v1/auth/token/renew-self > /dev/null
