#cloud-config
coreos:
  update:
    reboot-strategy: off

  units:
    - name: install-ssh-helper.service
      command: start
      content: |
        [Service]
        Type=oneshot
        ExecStart=/opt/bin/install-ssh-helper.sh

    - name: vault-login.service
      command: start
      content: |
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/opt/bin/vault-login.sh

    - name: vault-renew-token.service
      content: |
        [Service]
        Type=simple
        ExecStart=/opt/bin/vault-renew-token.sh

    - name: vault-renew-token.timer
      command: start
      content: |
        [Timer]
        OnActiveSec=12h
        OnUnitActiveSec=12h

    - name: kubelet-certs.service
      command: start
      content: |
        [Unit]
        Before=kubelet.service

        Requires=vault-login.service
        After=vault-login.service

        [Service]
        Type=simple

        ExecStart=/opt/bin/kubelet-certs.sh
        ExecStartPost=/bin/bash -c "systemctl kill -s HUP kubelet.service || true"

    - name: kubelet-certs.timer
      command: start
      content: |
        [Timer]
        OnUnitActiveSec=12h

    - name: docker.service
      command: start
      drop-ins:
        - name: 99-mount-flags.conf
          content: |
            [Unit]
            After=flanneld.service

            [Service]
            MountFlags=shared

    - name: awscli.service
      command: start
      content: |
        [Unit]
        Requires=docker.service
        After=docker.service

        [Service]
        Type=oneshot
        Environment=DOCKER_CONTENT_TRUST=1
        ExecStart=/usr/bin/docker build -t localhost/awscli /opt/awscli/

    - name: ecr-login.service
      command: start
      content: |
        [Unit]
        Requires=awscli.service
        After=awscli.service

        [Service]
        Type=simple
        ExecStart=/opt/bin/ecr-login.sh

    - name: ecr-login.timer
      command: start
      content: |
        [Timer]
        OnUnitActiveSec=12h

    - name: flanneld.service
      command: start
      drop-ins:
        - name: 40-ssl-config.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/test -f /etc/ssl/kubelet/ca.pem
            ExecStartPre=/usr/bin/test -f /etc/ssl/kubelet/cert.pem
            ExecStartPre=/usr/bin/test -f /etc/ssl/kubelet/privkey.pem
        - name: 99-client.conf
          content: |
            [Service]
            Environment=ETCD_SSL_DIR=/etc/ssl/kubelet
            Environment=FLANNELD_REMOTE=${kube_fqdn}:8888
            Environment=FLANNELD_REMOTE_CAFILE=/etc/ssl/kubelet/ca.pem
            Environment=FLANNELD_REMOTE_CERTFILE=/etc/ssl/kubelet/cert.pem
            Environment=FLANNELD_REMOTE_KEYFILE=/etc/ssl/kubelet/privkey.pem

    - name: kubelet.service
      command: start
      content: |
        [Unit]
        Requires=docker.service flanneld.service
        After=docker.service flanneld.service

        [Service]
        Restart=always
        RestartSec=10
        TimeoutStartSec=300

        ExecStartPre=/usr/bin/test -f /etc/ssl/kubelet/ca.pem
        ExecStartPre=/usr/bin/test -f /etc/ssl/kubelet/cert.pem
        ExecStartPre=/usr/bin/test -f /etc/ssl/kubelet/privkey.pem

        Environment=KUBELET_ACI=${hyperkube}
        Environment=KUBELET_VERSION=${kube_version}
        Environment="RKT_OPTS=--volume dns,kind=host,source=/etc/resolv.conf \
        --mount volume=dns,target=/etc/resolv.conf \
        --volume rkt,kind=host,source=/opt/bin/host-rkt \
        --mount volume=rkt,target=/usr/bin/rkt \
        --volume var-lib-rkt,kind=host,source=/var/lib/rkt \
        --mount volume=var-lib-rkt,target=/var/lib/rkt \
        --volume stage,kind=host,source=/tmp \
        --mount volume=stage,target=/tmp \
        --volume var-log,kind=host,source=/var/log \
        --mount volume=var-log,target=/var/log \
        --volume kubelet-ssl,kind=host,source=/etc/ssl/kubelet \
        --mount volume=kubelet-ssl,target=/etc/ssl/kubelet \
        --volume kube-ca,kind=host,source=/etc/ssl/kube/ca.pem \
        --mount volume=kube-ca,target=/etc/ssl/kube/ca.pem"

        ExecStartPre=/usr/bin/mkdir -p /var/log/containers
        ExecStart=/usr/lib/coreos/kubelet-wrapper \
          --api-servers=https://${kube_fqdn} \
          --node-labels=role=worker,class=${worker_class} \
          --tls-cert-file=/etc/ssl/kubelet/cert.pem \
          --tls-private-key-file=/etc/ssl/kubelet/privkey.pem \
          --config=/etc/kubernetes/manifests \
          --kubeconfig=/etc/kubernetes/kubelet/kubeconfig.yaml \
          --hostname-override=$private_ipv4 \
          --cluster-dns=10.0.0.10 \
          --cluster-domain=cluster.local \
          --register-schedulable=false \
          --allow-privileged --v=2 --logtostderr=true

write_files:
  - path: /etc/ssl/vault/ca.pem
    permissions: 0600
    encoding: base64
    content: |
      ${vault_ca_cert_pem}

  - path: /opt/bin/install-ssh-helper.sh
    permissions: 0700
    content: |
      #!/bin/bash
      set -eo pipefail

      log="/var/log/vault-ssh.log"
      replace="auth\t\tsufficient\tpam_exec.so quiet expose_authtok log=$log /opt/bin/ssh-helper"
      cp /usr/lib64/pam.d/{sshd,system-remote-login,system-login,system-auth} /etc/pam.d/
      sed -r -i /etc/pam.d/system-auth -e "s,^(auth.*required.*pam_deny.so)$,$replace\\n\1,g"

  - path: /opt/bin/ssh-helper
    permissions: 0700
    content: |
      #! /bin/bash
      CMD="docker run -i --rm --net=host -e PAM_USER=$PAM_USER ${ssh_helper}"
      eval $CMD $*

  - path: /opt/bin/vault-login.sh
    permissions: 0700
    content: |
      #!/bin/bash
      set -eo pipefail

      nonce="$(cat /etc/machine-id | base64)"
      pkcs="$(curl -sSf ${vault_curl_opts} --cacert /etc/ssl/vault/ca.pem \
        http://169.254.169.254/latest/dynamic/instance-identity/pkcs7 | tr -d '\n')"

      curl -sSf ${vault_curl_opts} --cacert /etc/ssl/vault/ca.pem \
        -X POST -H "Content-Type: application/json" \
        -d "{\"pkcs7\":\"$pkcs\",\"role\":\"${vault_instance_role}\",\"nonce\":\"$nonce\"}" \
        ${vault_address}/v1/auth/aws-ec2/login | \
        sed -re 's/.*"client_token":"([^"]*)".*/\1/g' > /root/.vault-token

  - path: /opt/bin/vault-renew-token.sh
    permissions: 0700
    content: |
      #!/bin/bash
      set -eo pipefail

      token="$(cat /root/.vault-token)"
      curl -sSf ${vault_curl_opts} --cacert /etc/ssl/vault/ca.pem \
        -X POST -H "X-Vault-Token: $token" \
        ${vault_address}/v1/auth/token/renew-self > /dev/null

  - path: /opt/bin/kubelet-certs.sh
    permissions: 0700
    content: |
      #!/bin/bash
      set -eo pipefail

      mkdir -p /etc/ssl/kubelet
      curl -sSf ${vault_curl_opts} --cacert /etc/ssl/vault/ca.pem \
        -o /etc/ssl/kubelet/ca.pem -z /etc/ssl/kubelet/ca.pem \
        ${vault_address}/v1/${kubelet_pki_mount}/ca/pem

      token="$(cat /root/.vault-token)"
      json=$(curl -sSf ${vault_curl_opts} --cacert /etc/ssl/vault/ca.pem \
        -X POST -H "X-Vault-Token: $token" \
        -d '{"common_name":"kubelet", "ip_sans": "$private_ipv4"}' \
        ${vault_address}/v1/${kubelet_pki_mount}/issue/${kubelet_pki_role})

      sed -re 's/.*"certificate":"([^"]*)".*/\1/g' \
        -e 's/\\n/\n/g' > /etc/ssl/kubelet/cert.pem <<< $json
      sed -re 's/.*"private_key":"([^"]*)".*/\1/g' \
        -e 's/\\n/\n/g' > /etc/ssl/kubelet/privkey.pem <<< $json

  - path: /opt/awscli/Dockerfile
    content: |
      FROM alpine:3.4

      RUN mkdir -p /aws && \
        apk -Uuv add groff less python py-pip jq && \
        pip install awscli && \
        apk --purge -v del py-pip && \
        rm /var/cache/apk/*

      WORKDIR /aws
      ENTRYPOINT ["aws"]

  - path: /opt/bin/ecr-login.sh
    permissions: 0700
    content: |
      #! /bin/bash
      set -eo pipefail

      eval $(docker run --rm -e AWS_DEFAULT_REGION=${region} localhost/awscli ecr get-login)

  - path: /opt/bin/host-rkt
    permissions: 0755
    owner: root:root
    content: |
      #!/bin/sh
      # https://github.com/coreos/rkt/issues/2878
      exec nsenter -m -u -i -n -p -t 1 -- /usr/bin/rkt "$@"

  - path: /etc/kubernetes/kubelet/kubeconfig.yaml
    content: |
      apiVersion: v1
      kind: Config
      current-context: kubelet
      clusters:
        - name: kubernetes
          cluster:
            certificate-authority: /etc/ssl/kubelet/ca.pem
            server: https://${kube_fqdn}
      contexts:
        - name: kubelet
          context:
            cluster: kubernetes
            user: kubelet
      users:
        - name: kubelet
          user:
            client-certificate: /etc/ssl/kubelet/cert.pem
            client-key: /etc/ssl/kubelet/privkey.pem
