---
apiVersion: v1
kind: Service
metadata:
  name: kube-controller-manager
  namespace: kube-system
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '10252'
  labels:
    name: kube-controller-manager
spec:
  selector:
    app: kubernetes
    component: controller-manager
  ports:
  - name: metrics
    port: 10252
    protocol: TCP

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-controller-manager
  labels:
    app: kubernetes
    component: controller-manager
spec:
  template:
    metadata:
      labels:
        app: kubernetes
        component: controller-manager
    spec:
      nodeSelector:
        role: controller
      hostNetwork: true
      imagePullPolicy: Always
      containers:
        - name: kube-controller-manager
          image: ${hyperkube}
          command:
              - /hyperkube
              - controller-manager
              - --master=https://${kube_fqdn}
              - --kubeconfig=/etc/kubernetes/controller/kubeconfig.yaml
              - --leader-elect=true
              - --root-ca-file=/etc/ssl/kube/ca.pem
              - --service-account-private-key-file=/etc/kubernetes/service-account/privkey.pem
          livenessProbe:
            httpGet:
              host: 127.0.0.1
              path: /healthz
              port: 10252
            initialDelaySeconds: 15
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /etc/kubernetes/controller/kubeconfig.yaml
              name: kubeconfig
              readOnly: true
            - mountPath: /etc/ssl/kube/ca.pem
              name: kube-ca
              readOnly: true
            - mountPath: /etc/ssl/controller
              name: controller-certs
              readOnly: true
            - mountPath: /etc/ssl/certs
              name: ssl-certs-host
              readOnly: true
            - mountPath: /etc/kubernetes/service-account/privkey.pem
              name: service-account
              readOnly: t
        volumes:
          - hostPath:
              path: /usr/share/ca-certificates
            name: ssl-certs-host
          - hostPath:
              path: /etc/ssl/kube/ca.pem
            name: kube-ca
          - hostPath:
              path: /etc/ssl/controller/
            name: controller-certs
          - hostPath:
              path: /etc/kubernetes/controller/kubeconfig.yaml
            name: kubeconfig
          - hostPath:
              path: /etc/kubernetes/service-account/privkey.pem
            name: service-account
