---
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "A managed Vault Secret."
metadata:
  name: "secret.stable.vaultproject.io"
versions:
  - name: v1

#TODO add a secret for vault address and vault token

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kube-vault-manager
  name: kube-vault-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-vault-manager
      name: kube-vault-manager
    spec:
      containers:
        - name: kube-vault-manager
          image: roboll/kube-vault-manager:0.2
          imagePullPolicy: Always
          env:
            - name: VAULT_ADDR
              value: ${vault_address}
            - name: VAULT_TOKEN
              value: ${vault_token}
          volumeMounts:
            - name: ssl
              mountPath: /etc/ssl/certs
        - name: kubectl
          image: kelseyhightower/kubectl:1.2.3
          args:
            - proxy
      volumes:
        - name: ssl
          hostPath:
            path: /usr/share/ca-certificates
