---
apiVersion: v1
kind: Service
metadata:
  name: kube-ingress-default
  namespace: kube-system
  labels:
    app: kube-ingress
    component: default-backend
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: kube-ingress
    component: default-backend

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-ingress-default
  namespace: kube-system
  labels:
    app: kube-ingress
    component: default-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-ingress
        component: default-backend
    spec:
      containers:
      - name: default-http-backend
        image: gcr.io/google_containers/defaultbackend:1.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi

---
apiVersion: v1
kind: Service
metadata:
  name: kube-ingress-nginx
  namespace: kube-system
  labels:
    app: kube-ingress
    component: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: kube-ingress
    component: nginx

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-ingress-nginx
data:
  proxy-connect-timeout: "15"
  proxy-read-timeout: "600"
  proxy-send-imeout: "600"
  hsts-include-subdomains: "false"
  body-size: "64m"

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-ingress-nginx
  namespace: kube-system
  labels:
    app: kube-ingress
    component: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-ingress
        component: nginx
    spec:
      containers:
        - image: roboll/nginx-ingress-controller:0.8.2
          name: nginx
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10249
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 80
            - containerPort: 443
          args:
            - /nginx-ingress-controller
            - --default-backend-service=kube-system/kube-ingress-default
            - --nginx-configmap=kube-system/kube-ingress-nginx

#---
#apiVersion: extensions/v1beta1
#kind: Deployment
#metadata:
#  name: kube-ingress-dns
#  namespace: kube-system
#  labels:
#    app: kube-ingress
#    component: dns
#spec:
#  replicas: 1
#  template:
#    metadata:
#      labels:
#        app: kube-ingress
#        component: dns
#    spec:
#      containers:
#        - image: roboll/kube-dns-controller:latest
#          imagePullPolicy: Always
#          name: dns-controller
#          args:
#            - /dns-controller
#            - --publish-service=kube-system/kube-ingress-nginx
#          env:
#            - name: AWS_DEFAULT_REGION
#              value: us-east-1
#            - name: AWS_ACCESS_KEY_ID
#              valueFrom:
#                secretKeyRef:
#                  name: kube-ingress-dns-aws
#                  key: access-key
#            - name: AWS_SECRET_ACCESS_KEY
#              valueFrom:
#                secretKeyRef:
#                  name: kube-ingress-dns-aws
#                  key: secret-key
#          volumeMounts:
#            - name: ca-certs
#              mountPath: /etc/ssl/certs
#      volumes:
#        - name: ca-certs
#          hostPath:
#            path: /usr/share/ca-certificates
