---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-proxy-config
  namespace: kube-system
data:
  kubeconfig: |-
    apiVersion: v1
    kind: Config
    users:
      - name: kube-proxy
        user:
          token: {{token}}
    clusters:
      - name: local
        cluster:
          certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          server: https://${kube_fqdn}
    contexts:
      - context:
          cluster: local
          user: kube-proxy
        name: service-account-context
    current-context: service-account-context

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-proxy
  labels:
    app: kubernetes
    component: proxy
spec:
  template:
    metadata:
      labels:
        app: kubernetes
        component: proxy
    spec:
      hostNetwork: true
      containers:
        - name: kube-proxy
          image: ${hyperkube}:${kube_version}
          command:
            - /bin/bash
            - -c
            - "sed -i /etc/kubeconfig/kubeconfig \
                -e s,{{token}},$(cat /var/run/secrets/kubernetes.io/serviceaccount/token),g && \
                source /etc/environment && \
                /hyperkube proxy \
                  --master=https://${kube_fqdn} \
                  --kubeconfig=/etc/kubeconfig/kubeconfig \
                  --hostname-override=$COREOS_PRIVATE_IPV4 \
                  --proxy-mode=iptables"
          volumeMounts:
            - name: kubeconfig
              mountPath: /etc/kubeconfig
            - name: env
              mountPath: /etc/environment
          securityContext:
            privileged: true
      volumes:
        - name: env
          hostPath:
            path: /etc/environment
        - name: kubeconfig
          configMap:
            name: kube-proxy-config
