#cloud-config
coreos:
  update:
    reboot-strategy: off

  units:
    - name: vault-ssh.service
      command: start
      content: |
        [Service]
        Type=oneshot

        ExecStartPre=/usr/bin/rkt fetch --trust-keys-from-https ${vault_ssh_image}
        ExecStart=/usr/bin/rkt image extract --rootfs-only --overwrite ${vault_ssh_image} /tmp/vault-ssh
        ExecStartPost=/tmp/vault-ssh/link.sh

    - name: docker.service
      command: start
      drop-ins:
        - name: 99-mount-flags.conf
          content: |
            [Service]
            MountFlags=shared

    - name: kubelet.service
      command: start
      content: |
        [Unit]
        Requires=docker.service
        After=docker.service

        [Service]
        Restart=always
        RestartSec=10

        ExecStartPre=/usr/bin/mkdir -p /var/run/kubelet

        ExecStartPre=/usr/bin/docker run \
          -e VAULT_ADDR=${vault_address} \
          -e VAULT_AUTH_ROLE=${vault_instance_role} \
          -e KUBE_PKI_MOUNT=${kube_pki_mount} \
          --volume /etc/kubernetes/manifests/:/etc/kubernetes/manifests/ \
          quay.io/roboll/kube-bootstrap:alpha /opt/bin/copy-registrar.sh

        ExecStart=/usr/bin/docker run \
          --volume=/:/rootfs/:ro \
          --volume=/sys/:/sys/:ro \
          --volume=/dev/:/dev/ \
          --volume=/var/run/:/var/run/:rw \
          --volume=/var/lib/secrets/:/var/lib/secrets/ \
          --volume=/var/lib/docker/:/var/lib/docker/:rw \
          --volume=/var/lib/kubelet/:/var/lib/kubelet/:shared \
          --net=host \
          --pid=host \
          --privileged=true \
          ${hyperkube}:${kube_version} \
            /hyperkube kubelet \
              --require-kubeconfig=true \
              --kubeconfig=/var/lib/kubelet/kubeconfig\
              --lock-file=/var/run/kubelet/lock \
              --exit-on-lock-contention=true \
              --node-labels=role=worker,class=${worker_class} \
              --allow-privileged=true

write_files:
  - path: /etc/ssl/vault/ca.pem
    permissions: 0600
    encoding: base64
    content: |
      ${vault_ca_cert_pem}

  - path: /etc/vault/ssh.hcl
    permissions: 0600
    content: |
      allowed_roles = "*"
      vault_addr = "${vault_address}"
      ca_cert = "/etc/ssl/vault/ca.pem"

  - path: /var/lib/kubelet/kubeconfig
    content: |
      apiVersion: v1
      kind: Config
      current-context: kubelet
      clusters:
        - name: kubernetes
          cluster:
            server: https://${kube_fqdn}
            certificate-authority: /var/lib/kubelet/certs/ca.pem
      contexts:
        - name: kubelet
          context:
            cluster: kubernetes
            user: kubelet
      users:
        - name: kubelet
          user:
            client-certificate: /var/lib/kubelet/certs/cert.pem
            client-key: /var/lib/kubelet/certs/key.pem
